- hosts: mysql
  remote_user: root
  become: yes
  vars:
    mysql_binary_install_dir: "/usr/local"
    mysql_data_dir: "/data/mysql"
    tar_directory_name: "mysql-5.7.34-el7-x86_64"
    mysql_port: "3306"
    mysql_new_root_password: "123456"
    innodb_buffer_pool_size: "2G"
    mysql_socket_path: "/tmp/mysql.sock"
    mysql_new_adminroot_username: "adminroot"
    mysql_new_adminroot_password: "123456"
    mysql_new_adminroot_host: "%"
    mysql_new_adminroot_priv: "*.*:ALL"
    mysql_replication_username: "repl"
    mysql_replication_password: "123456"
    mysql_replication_priv: "*.*:replication slave"

  tasks:
    - name: Make sure the MySQL service is running
      service:
        name: mysql
        state: started
 
    - name: Set up the MySQL master server
      set_fact:
        mysql_master_ip: "{{ hostvars[item]['ansible_ssh_host'] }}"
      when: hostvars[item]['identity'] == 'master'
      with_items: "{{ groups[group_names.0] }}"

    - name: Set up the MySQL slave server
      set_fact:
        mysql_slave_ips: "{{ ansible_ssh_host }}"
      when: identity == 'slave' and inventory_hostname in groups[group_names.0]

    - name: Get the master log file name and location
      shell: "{{ mysql_binary_install_dir}}/mysql/bin/mysql -uroot -p'{{ mysql_new_root_password }}' -e 'show master status \\G' | grep -E 'File|Position'"
      register: "master_status"
      #delegate_to: "{{ mysql_master_ip }}"
      when: identity == 'master'

#    - name: backup master database
#      become: true
#      shell: "{{ mysql_binary_install_dir }}/mysql/bin/mysqldump -uroot -p'{{ mysql_new_root_password }}' --set-gtid-purged=OFF --all-databases > /root/all-databases.sql"
#      delegate_to: "{{ mysql_master_ip }}"
#      when: identity == 'master'
    - name: backup master databases
      become: true
      mysql_db:
        login_unix_socket: "{{ mysql_socket_path }}"
        login_host: "localhost"
        login_user: "root"
        login_password: "{{ mysql_new_root_password }}"
        login_port: "{{ mysql_port }}"
        state: "dump"
        name: "all"
        target: "/root/all-databases.sql"
        dump_extra_args: "--set-gtid-purged=OFF"
      delegate_to: "{{ mysql_master_ip }}"
      when: identity == 'master'

    - name: Transfer the backup database to the local
      become: true
      fetch:
        src: "/root/all-databases.sql"
        dest: "/tmp/"
        flat: yes
      delegate_to: "{{ mysql_master_ip }}"
      when: identity == 'master'

    - name: Transfer the backup database to the slave server
      become: true
      copy:
        src: "/tmp/all-databases.sql"
        dest: "/root/all-databases.sql"
      when: identity == 'slave'

    - name: Restore database on the slave servers
      become: true
      shell: "{{ mysql_binary_install_dir}}/mysql/bin/mysql -u root -p{{ mysql_new_root_password }} < /root/all-databases.sql"
      when: identity == 'slave' 

    - name: Create mysql master-slave replication account repl
      become: true
      mysql_user:
        login_unix_socket: "{{ mysql_socket_path }}"
        login_host: "localhost"
        login_user: "root"
        login_password: "{{ mysql_new_root_password }}"
        login_port: "{{ mysql_port }}"
        name: "{{ mysql_replication_username }}"
        password: "{{ mysql_replication_password }}"
        host: "{{ item }}"
        priv: "{{ mysql_replication_priv }}"
        state: present
      delegate_to: "{{ mysql_master_ip }}"
      with_items: "{{ groups[group_names.0] | map('extract', hostvars, ['ansible_ssh_host']) | join(',') | split(',') }}"
      when: identity == 'master'

    - name: Set the master-slave relationship
      become: true
      mysql_replication:
        login_unix_socket: "{{ mysql_socket_path }}"
        login_host: "localhost"
        login_user: "root"
        login_password: "{{ mysql_new_root_password }}"
        login_port: "{{ mysql_port }}"
        mode: "changeprimary"
        primary_host: "{{ mysql_master_ip }}"
        primary_user: "{{ mysql_replication_username }}"
        primary_password: "{{ mysql_replication_password }}"
        primary_port: "{{ mysql_port }}"
        #primary_log_file: "{{ master_status.stdout_lines[0].split(':')[1] | trim }}"
        #primary_log_pos: "{{ master_status.stdout_lines[1].split(':')[1] | trim }}"
        primary_auto_position: 1
      #when: identity == 'slave' and 'File:' in master_status.stdout_lines[0] and 'Position:' in master_status.stdout_lines[1]
      when: identity == 'slave'

    - name: Start master-slave replication
      become: true
      mysql_replication:
        login_unix_socket: "{{ mysql_socket_path }}"
        login_host: "localhost"
        login_user: "root"
        login_password: "{{ mysql_new_root_password }}"
        login_port: "{{ mysql_port }}"
        mode: "startreplica"
      when: identity == 'slave'

    - name: Start MySQL service on the slave servers
      become: true
      mysql_replication:
        login_unix_socket: "{{ mysql_socket_path }}"
        login_host: "localhost"
        login_user: "root"
        login_password: "{{ mysql_new_root_password }}"
        login_port: "{{ mysql_port }}"
        mode: "getreplica"
      when: identity == 'slave'

    - name: create adminroot user
      become: true
      mysql_user:
        login_unix_socket: "{{ mysql_socket_path }}"
        login_host: "localhost"
        login_user: "root"
        login_password: "{{ mysql_new_root_password }}"
        login_port: "{{ mysql_port }}"
        name: "{{ mysql_new_adminroot_username }}"
        password: "{{ mysql_new_adminroot_password }}"
        host: "{{ mysql_new_adminroot_host }}"
        priv: "{{ mysql_new_adminroot_priv }}"
        state: "present"
      when: identity == 'master'
