apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.26.0
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
    inhibit_rules:
    - equal: ["namespace", "alertname"]
      source_matchers:
        - severity="critical"
      target_matchers:
        - severity=~"warning|info"
    - equal: ["namespace", "alertname"]
      source_matchers:
        - severity="warning"
      target_matchers:
        - severity="info"
    receivers:
    - name: 'null'
    - name: "webhook-prometheusalert-lark"
      webhook_configs:
      - url: "http://a3613ee828c594e5ca6f7971fcb2d390-378400107.ap-southeast-1.elb.amazonaws.com:8060/prometheusalert?type=fs&tpl=prometheus-fs&fsurl=https://open.larksuite.com/open-apis/bot/v2/hook/xxxxxxxxx"
        send_resolved: true
    route:
      group_by: ["alertname", "namespace"]
      group_interval: 5m
      group_wait: 10s
      receiver: "webhook-prometheusalert-lark"
      repeat_interval: 12h
      routes:
      - matchers:
        - alertname=~"InfoInhibitor|Watchdog|CPUThrottlingHigh"
        receiver: 'null'
type: Opaque
