host: "mysql"
mysql_version: "5.7.34"
packages_path: "../files"
download_path: "/software"
mysql_binary_install_dir: "/usr/local"
mysql_data_dir: "/data/mysql"
tar_directory_name: "mysql-5.7.34-el7-x86_64"
mysql_port: "3306"
mysql_new_root_password: "123456"
innodb_buffer_pool_size: "2G"
mysql_socket_path: "/tmp/mysql.sock"
mysql_new_adminroot_username: "adminroot"
mysql_new_adminroot_password: "123456"
mysql_new_adminroot_host: "%"
mysql_new_adminroot_priv: "*.*:ALL"
mysql_replication_username: "repl"
mysql_replication_password: "123456"
mysql_replication_priv: "*.*:replication slave"
