apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter-svc
  namespace: monitoring
spec:
  selector:
    k8s-app: kafka-exporter
  ports:
  - name: http-metrics
    protocol: TCP
    port: 9308
    targetPort: 9308
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kafka-exporter
  template:
    metadata:
      labels:
        k8s-app: kafka-exporter
    spec:
      containers:
      - name: kafka-exporter
        imagePullPolicy: IfNotPresent
        image: danielqsj/kafka-exporter:latest
        args:
          - --kafka.server=172.25.26.141:9092
          - --kafka.server=172.25.27.157:9092
          - --kafka.server=172.25.26.87:9092
        ports:
        - name: http-metrics
          containerPort: 9308
          protocol: TCP
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
