apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-instances-targets
  namespace: monitoring
data:
  redis-instances-targets.json: |
    [
      {
          "targets": [ "redis://192.168.26.141:6380", "redis://192.168.26.141:6381", "redis://192.168.27.157:6380", "redis://192.168.27.157:6381", "redis://192.168.26.87:6380", "redis://192.168.26.87:6381" ],
          "labels": { "cluster_name": "redis_cluster" }
      }
    ]
