apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-pwd-file
  namespace: monitoring
data:
  redis-pwd-file.json: |
    {
        "redis://192.168.26.141:6380": "2m4HcYfdiFsdjkfkgj",
        "redis://192.168.26.141:6381": "2m4HcYfdiFsdjkfkgj",
        "redis://192.168.27.157:6380": "2m4HcYfdiFsdjkfkgj",
        "redis://192.168.27.157:6381": "2m4HcYfdiFsdjkfkgj",
        "redis://192.168.26.87:6380": "2m4HcYfdiFsdjkfkgj",
        "redis://192.168.26.87:6381": "2m4HcYfdiFsdjkfkgj"
    }
