apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-exporter
  name: zookeeper-exporter-svc
  namespace: monitoring
spec:
  selector:
    app: zookeeper-exporter
  ports:
  - name: http-metrics
    port: 9141
    protocol: TCP
    targetPort: 9141
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-exporter
  template:
    metadata:
      labels:
        app: zookeeper-exporter
    spec:
      containers:
      - name: zookeeper-exporter
        image: dabealu/zookeeper-exporter:v0.1.13
        imagePullPolicy: IfNotPresent
        args:
        - --zk-hosts="192.168.26.141:2181,192.168.27.157:2181,192.168.26.87:2181"
        ports:
        - name: http-metrics
          containerPort: 9141
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
